site_name: Threat Matrix for Kubernetes
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
  logo: assets/Microsoft.png
  favicon: assets/mdc.png
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
extra_css:
  - stylesheets/extra.css
nav:
  - Tactics: 
    - 'index.md'
    - Initial Access:
      - 'tactics/InitialAccess/index.md'
      - Using Cloud Credentials: 'techniques/Using Cloud Credentials.md'
      - Compromised Image In Registry: 'techniques/Compromised Image In Registry.md'
      - Kubeconfig file: 'techniques/Kubeconfig file.md'
      - Application Vulnerability: 'techniques/Application Vulnerability.md'
      - Exposed Sensitive Interfaces: 'techniques/Exposed sensitive interfaces.md'
    - Execution:
      - 'tactics/Execution/index.md'
      - Exec Into Container: 'techniques/Exec into container.md'
      - Bash/cmd Inside Container: 'techniques/bash or cmd inside container.md'
      - New Container: 'techniques/New Container.md'
      - Application Exploit (RCE): 'techniques/Application Exploit (RCE).md'
      - SSH Server Running Inside Container: 'techniques/SSH server running inside container.md'
      - Sidecar Injection: 'techniques/Sidecar Injection.md'
    - Persistence:
      - 'tactics/Persistence/index.md'
      - Backdoor Container: 'techniques/Backdoor container.md'
      - Writable hostPath Mount: 'techniques/Writable hostPath mount.md'
      - Kubernetes CronJob: 'techniques/Kubernetes CronJob.md'
      - Malicious Admission Controller: 'techniques/Malicious admission controller.md'
      - Container Service Account: 'techniques/container service account.md'
      - Static Pods: 'techniques/Static Pods.md'
    - Privilege Escalation:
      - 'tactics/PrivilegeEscalation/index.md'
      - Privileged Container: 'techniques/Privileged container.md'
      - Cluster-admin Binding: 'techniques/Cluster-admin binding.md'
      - Writable hostPath Mount: 'techniques/Writable hostPath mount.md'
      - Access Cloud Resources: 'techniques/Access cloud resources.md'
    - Defense Evasion:
      - 'tactics/DefenseEvasion/index.md'
      - Clear Container Logs: 'techniques/Clear container logs.md'
      - Delete Kubernetes Events: 'techniques/Delete K8S events.md'
      - Pod or Container Name Similarily: 'techniques/Pod or container name similarily.md'
      - Connect from Proxy Server: 'techniques/Connect from Proxy server.md'
    - Credential Access:
      - 'tactics/CredentialAccess/index.md'
      - List Kubernetes Secrets: 'techniques/List K8S secrets.md'
      - Mount Service Principal: 'techniques/Mount service principal.md'
      - Container Service Account: 'techniques/container service account.md'
      - Application Credentials in Configuration Files: 'techniques/Application credentials in configuration files.md'
      - Access Managed Identity Credentials: 'techniques/Access managed identity credentials.md'
      - Malicious Admission Controller: 'techniques/Malicious admission controller.md'
    - Discovery:
      - 'tactics/Discovery/index.md'
      - Access Kubernetes API Server: 'techniques/Access the K8S API server.md'
      - Access Kubelet API: 'techniques/Access Kubelet API.md'
      - Network Mapping: 'techniques/Network mapping.md'
      - Access Kubernetes Dasbhoard: 'techniques/Access Kubernetes dasbhoard.md'
      - Instance Metadata API: 'techniques/Instance Metadata API.md'
    - Lateral Movement:
      - 'tactics/LateralMovement/index.md'
      - Access Cloud Resources: 'techniques/Access cloud resources.md'
      - Container Service Account: 'techniques/container service account.md'
      - Cluster Internal Networking: 'techniques/Cluster internal networking.md'
      - Application Credentials in Configuration Files: 'techniques/Application credentials in configuration files.md'
      - Writable hostPath Mount: 'techniques/Writable hostPath mount.md'
      - CoreDNS Poisoning: 'techniques/CoreDNS poisoning.md'
      - ARP poisoning and IP spoofing: 'techniques/ARP poisoning and IP spoofing.md'
    - Collection:
      - 'tactics/Collection/index.md'
      - Images from a Private Registry: 'techniques/images from a private registry.md'
      - Collecting Data from Pod: 'techniques/Collecting Data from Pod.md'
    - Impact:
      - 'tactics/Impact/index.md'
      - Data Destruction: 'techniques/Data destruction.md'
      - Resource Hijacking: 'techniques/Resource hijacking.md'
      - Denial of Service: 'techniques/Denial of service.md'
  - Mitigations: 
    - 'mitigations/index.md'
    - Multi-factor Authentication: 'mitigations/MS-M9001 Multi-factor Authentication.md'
    - Restrict access to the API server using IP firewall: 'mitigations/MS-M9002 Restrict access to the API server using IP firewall.md'
    - Adhere to least-privilege principle: 'mitigations/MS-M9003 Adhere to least-privilege principle.md'
    - Secure CI/CD envrionment: 'mitigations/MS-M9004 Secure CI CD environment.md'
    - Image Assurance Policy: 
      - 'mitigations/MS-M9005/index.md'
      - Gate generated images in CI/CD pipeline: 'mitigations/MS-M9005/MS-M9005.001 Gate generated images in CI CD pipeline.md'
      - Gate images pushed to registries: 'mitigations/MS-M9005/MS-M9005.002 Gate images pushed to registries.md'
      - Gate images deployed to Kubenertes cluster: 'mitigations/MS-M9005/MS-M9005.003 Gate images deployed to Kubenertes cluster.md'
    - Enable Just In Time access to API server: 'mitigations/MS-M9006 Enable Just In Time access to API server.md'
    - Network Intrusion Prevention: 'mitigations/MS-M9007 Network Intrusion Prevention.md'
    - Limit Access to Services Over Network: 'mitigations/MS-M9008 Limit Access to Services Over Network.md'
    - Require Strong Authentication to Services: 'mitigations/MS-M9009 Require Strong Authentication to Services.md'
    - Restrict Exec Commands on Pods: 'mitigations/MS-M9010 Restrict Exec Commands on Pods.md'
    - Restrict Container Runtime using LSM: 'mitigations/MS-M9011 Restrict Container Runtime using LSM.md'
    - Remove Tools from Container Images: 'mitigations/MS-M9012 Remove Tools from Container Images.md'
    - Limit Container Capabilities: 'mitigations/MS-M9013 Limit Container Capabilities.md'
    - Network Segmentation: 'mitigations/MS-M9014 Network Segmentation.md'
    - Avoid Running Management Interface on Containers: 'mitigations/MS-M9015 Avoid Running Management Interface on Containers.md'
    - Restrict File and Directory Permissions: 'mitigations/MS-M9016 Restrict File and Directory Permissions.md'
    - Ensure that pods meet defined Pod Security Standards: 'mitigations/MS-M9017 Ensure that pods meet defined Pod Security Standards.md'
    - Restricting cloud metadata API access: 'mitigations/MS-M9018 Restricting cloud metadata API access.md'
    - Allocate specific identities to pods: 'mitigations/MS-M9019 Allocate specific identities to pods.md'
    - Collect Logs to Remote Data Storage: 'mitigations/MS-M9020 Collect Logs to Remote Data Storage.md'
    - Restrict the usage of unauthenticated APIs in the Cluster: 'mitigations/MS-M9021 Restrict the usage of unauthenticated APIs in the Cluster.md'
  - About: 'about.md'